#!/bin/bash
#
#   Simple shell script to backup (archive) files/directories to
#   a local target while only keeping a set amount of generations.
#

VERSION="0.0.1"

## Must be resolvable by `date`
## prefix/suffix will be added later
BASE_NAME="%Y-%m-%d_%H:%M"

## will be set by the `argparse` 
_sources=""
_target=""
_prefix=""
_suffix=""
_keep=3
_ask=true

_install_target='/usr/bin/dups'

function usage() {
    local script=`basename "$0"`

    printf "usage: $script [options] [source [...]] [target]\n\n"
    printf "Options:\n"
    printf "  -p [prefix]       Prefix to add to the filename.\n"
    printf "  -s [suffix]       Suffix to add to the filename.\n"
    printf "  -g [generations]  Generations to keep.\n"
    printf "                    Set to 0 to keep infinite.\n"
    printf "                    Defaults to %s.\n" ${_keep}
    printf "  -y, --yes         Don't ask for confirmation.\n"
    printf "  --install         Install to system (%s)\n" "${_install_target}"
    printf "  --uninstall       Uninstall from system (%s)\n" "${_install_target}"
    printf "  -v, --version     Print version and exit\n"
    printf "  -h, --help        Show this help text.\n"
    printf "\n"
    printf "Notes:\n"
    printf "  - Deletion of old backups will take the prefix and suffix into\n"
    printf "    account. This means neither of these should be dynamic as\n"
    printf "    otherwise older version will not be deleted.\n"
}

function argparse() {
    while [ $# -gt 0 ]; do
        case $1 in
            "-g")
                _keep=$2
                shift
                ;;
            "-p")
                _prefix="$2"
                shift
                ;;
            "-s")
                _suffix="$2"
                shift
                ;;
            "-y"|"--yes")
                _ask=false
                ;;
            "-h"|"--help")
                usage
                exit 0
                ;;
            "-v"|"--version")
                echo "${VERSION}"
                exit 0
                ;;
            "--install")
                install
                exit 0
                ;;
            "--uninstall")
                uninstall
                exit 0
                ;;
            **)
                ## at least two args (source, target) are required
                if [ "$#" -lt 2 ]; then
                    usage
                    exit 1
                fi

                ## get all but last
                _sources=("$@")
                unset '_sources[-1]'

                ## get last
                _target="${!#}"
                _target="${_target%/}"

                break
                shift
                ;;
        esac

        shift
    done

    ## make sure we have a target
    if [ ! -d "${_target}" ]; then
        mkdir -p "${_target}"

        if [ ! $? -eq 0 ]; then
            log "Couldn't create target. Exiting!"
            exit 1
        fi
    fi

    ## must be an int
    if [[ ! "$_keep" =~ ^[0-9]+$ ]]; then
        log "Generations should be an integeter but it isn't, Exiting!"
        exit 1
    fi
}

function log() {
    echo -e "$@" >&2
}

function install() {
    ## check if target already exists
    if [ -f "${_install_target}" ]; then
        printf '"%s" already exists.\n' "${_install_target}"
        read -p "Proceed and overwrite [y/N]? " -n 1 -r
        printf "\n"

        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            printf "Installation canceled.\n"
            exit 0
        fi
    fi

    sudo cp "$0" "${_install_target}"
    if [ $? -eq 0 ]; then
        printf "Installation successful!\n"
    else
        printf "Installation failed!\n"
    fi
}

function uninstall() {
    if [ ! -f "${_install_target}" ]; then
        printf "Not installed, nothing to do!\n"
        exit 0
    fi

    read -p "Remove \"${_install_target}\" from your system? [y/N]? " -n 1 -r
    printf "\n"

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        printf "Uninstallation canceled.\n"
        exit 0
    fi

    sudo rm "${_install_target}"
    if [ $? -eq 0 ]; then
        printf "Uninstallation successful!\n"
    else
        printf "Uninstallation failed!\n"
    fi
}

function do_backup() {
    ## ask confirmation before starting backup
    if $_ask; then
        read -p "Start backup [Y/n]? " -n 1 -r
        REPLY="${REPLY:-y}"
        printf "\n"

        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 0
        fi
    fi

    ## create backup
    _target_file="${_target}/${_prefix}$(date +"${BASE_NAME}")${_suffix}.zip"
    zip -r "${_target_file}" "${_sources[@]}"

    ## delete old
    if [ ${_keep} -gt 0 ]; then
        ls -t "${_target}/${_prefix}"*"${_suffix}.zip" | awk "NR>${_keep}" | xargs -I {} rm -- {}
    fi
}

## do some argparsing
argparse "$@"

## do backup
do_backup
